### ISSUE TITLE
di.js npm

### ISSUE THREAD

**Issue by yjmoroz** [zxbodya/reactive-widgets#2]
What about to publish di.js to npm? ;)

**Comment by zxbodya** [comment]
I am planning to do that... 

But before publishing, I need to choose a name for a package or a for packages namespace(I am thinking about to publish few related packages at one namespace).

Also, I want to improve it a bit before publishing... 

For now DI does not have any meta data about declared services, so some error messages are not quite helpful. For example error message about cyclic dependencies is really hard to debug, since you will need to manually inspect all dependencies.

**Comment by yjmoroz** [comment]
I guess beta for now is good enough.

With following points I can try to help

**Comment by zxbodya** [comment]
Just published it, as `di1` (not creative but short and not used). 

https://www.npmjs.com/package/di1
http://github.com/zxbodya/di1
